services:
  Espin\FormNewsletterBundle\EventListener\FormNewsletter:
    public: true
    arguments:
      - '@Contao\CoreBundle\String\SimpleTokenParser'
      - '@contao.opt_in'
      - '@?monolog.logger.contao.cron'
    tags:
      - name: contao.hook
        hook: generatePage
        method: onActivateRecipient
      - name: contao.hook
        hook: prepareFormData
        method: onPrepareFormData
        priority: 200
